spring:
  cloud:
    gateway:
      default-filters:
      routes:
        - id: test
          uri: http://192.168.1.5:8080/
          predicates:
            - Path=/a/**
          filters:
            - RewritePath=/a/(?<segment>.*), /$\{segment}/
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG